### ISSUE TITLE
kr upgrade fails with "touch ~/.ssh/config: Operation not permitted"

### ISSUE THREAD

**Issue by achimnol** [KryptCo/homebrew-tap#4]
I have a manually managed version of .ssh/config with some addition by kryptonite's first install.
I just ran "kr upgrade" due to a update message shown in the iOS app, but it fails with the following message:

```
...
==> mkdir -p ~/.ssh
==> touch ~/.ssh/config
Last 15 lines from /Users/joongi/Library/Logs/Homebrew/kr/post_install.02.config:
2017-08-08 16:47:23 +0900

touch ~/.ssh/config

touch: /Users/joongi/.ssh/config: Operation not permitted

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kryptco/homebrew-tap/issues
```

Tried to change the permission of .ssh/config to 666, but no luck.
Retrying with `brew postinstall kryptco/tap/kr` did not help either.

**Comment by achimnol** [comment]
Q. How do I use "--with-no-ssh-config" option with "kr upgrade"?

```
> kr upgrade --with-no-ssh-config
Incorrect Usage.

NAME:
   kr upgrade - Upgrade Kryptonite on this workstation.

USAGE:
   kr upgrade [arguments...]
```

**Comment by kcking** [comment]
Thank you for reporting -- the recent brew update now uses the mac sandbox, breaking our formula. We will be moving the SSH config logic to `kr pair` today where you will have the option to not modify you SSH config at all. I'll post here once that's released.

**Comment by benmoss** [comment]
`brew reinstall --with-no-ssh-config kryptco/tap/kr` works, but `curl https://krypt.co/kr | sh` is probably simpler if you need to install right now.

**Comment by kcking** [comment]
We have released the new formula along with kr 2.2.7. ssh configuration is now all handled at `kr pair` time. Let us know if this helps!

**Comment by benmoss** [comment]
Worked for me. Thanks!

**Comment by kcking** [comment]
Great! Closing out the issue

**Comment by achimnol** [comment]
Now `kr upgrade` goes smoothly. :+1:
