### ISSUE TITLE
`kr upgrade` fails when Xcode is not installed

### ISSUE THREAD

**Issue by gmiroshnykov** [KryptCo/homebrew-tap#6]
I have Command Line Tools installed, but I don't have Xcode.
Most of the things installed via Homebrew are fine with this setup, but apparently the latest `kr` release broke something:

```
$ kr upgrade
Upgrade Kryptonite on this workstation? [y/N]
y
==> Upgrading 1 outdated package, with result:
kryptco/tap/kr 2.3.0
==> Upgrading kryptco/tap/kr
==> Cloning https://github.com/kryptco/kr.git
Updating /Users/laggyluke/Library/Caches/Homebrew/kr--git
==> Checking out tag 2.3.0
==> make install
Last 15 lines from /Users/laggyluke/Library/Logs/Homebrew/kr/01.make:
2017-11-22 19:37:24 +0100

make
install

rm -rf bin lib Frameworks
mkdir -p bin
mkdir -p lib
mkdir -p Frameworks
cd krbtle && xcodebuild -configuration Release -archivePath /private/tmp/kr-20171122-26273-g0cbqk/src/github.com/kryptco/kr/Frameworks -scheme krbtle-Package
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [all] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kryptco/homebrew-tap/issues
```

**Comment by kcking** [comment]
It looks like brew upgrade is trying to build from source instead of using the bottle, does `brew reinstall kr` work?

**Comment by gmiroshnykov** [comment]
Nope, `brew reinstall kr` does exactly the same thing, but now it helpfully references this very issue at the end :)

**Comment by kcking** [comment]
Nice :)

How about `brew uninstall kr` then `brew install kryptco/tap/kr`?

**Comment by gmiroshnykov** [comment]
Hm, that actually worked!
It downloaded a bottle instead of trying to compile it locally.
But now if I try `brew reinstall kr` it still fails with the same error.
I'm not familiar with inner workings of Homebrew, but this looks fishy.
BTW I also could reproduce this on a second laptop, both running High Sierra.

**Comment by kcking** [comment]
Great!

I'm looking into this now -- worst case `kr upgrade` will uninstall/reinstall to force the use of the bottle.

**Comment by tangrufus** [comment]
Same issue here.
`brew uninstall kr` then `brew install kryptco/tap/kr` works!

---

macOS High Sierra
Homebrew 1.3.8
Command line tools installed, but not Xcode.

**Comment by kcking** [comment]
Just pushed a formula change that should fix this. Please re-open if it happens again!

**Comment by gmiroshnykov** [comment]
I can confirm it works now.

Thanks a lot for being so responsive and for building this awesome product in the first place! :)

**Comment by kcking** [comment]
Great, thank you for reporting the issue!
